### ISSUE TITLE
Hi I have same PC kindly share the EFI files

### ISSUE THREAD

**Issue by sultanis** [KemonDream/Ryzentosh-5900hx-mofire-s500#1]
Thank you.

**Comment by KemonDream** [comment]
Oh grandly sorry, haven't seem this comment for month, I was new to GitHub. I will release the EFI files sooner or later after some organization>w<

**Comment by KemonDream** [comment]
But what was worth waiting for is that the latest version had fixed the wifi-m.2 slot issue :)

**Comment by KemonDream** [comment]
You can now download the EFI !)

**Comment by sultanis** [comment]
Thank you
